# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42acd68022ae05d5aecd16555b3c0839f6f21267f90f57716751eb7e066042a4a402a977a1c3970f992b1e04f78630eb8fc3e2a2fd55a55a9b573b8e24551ed6

test:
  secret_key_base: 0567862f06b837b9eb6ba848794ba801fd7bfef3a4fdb144e5f5ab22e2307e76d5b339b6b4ee0981881a9e33d89f6985e1ca401569ad3a51aca99c3c58abb18b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
